### ISSUE TITLE
Mockup pour formulaire de création / modification (consultation, clients, chiens, service)

### ISSUE THREAD

**Issue by Vidivanze** [CPNV-ES/PRW3_What-The-Dog#22]
## Story

- [x] Mockup formulaire de création de consultation
- [x] Mockup formulaire de création de client
- [x] Mockup formulaire de création de chien
- [x] Mockup formulaire de création de service

**Comment by SuperQuentin** [comment]
https://www.figma.com/file/J48X5DauKebNZ3SDaO7Jx3/What-the-dog?node-id=0%3A1
